# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Seattle Public Records
email: info@seattlepublicrecords.org
description: > # this means to ignore newlines until "baseurl:"
  A nonprofit news site with the goal of significantly increasing
  public control of government agencies operating inside the City of
  Seattle.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://seattlepublicrecords.org" # the base hostname & protocol for your site
twitter_username: seapubrecords
github_username:  seattlepublicrecords
permalink: /:categories/:title
post_dirs: false
# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
  - jekyll-feed
defaults:
  - scope:
        path: ""
        type: posts
    values:
        thumbnail: ""
        categories: ["news"]
        description: ""
        author: "Tim Clemans"
